version: 1.0.{build}
build:
  verbosity: minimal
  
environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Release
      COMPILER: MSVC15
      PLATFORM: Win32
    - COMPILER: MinGW-w64
      ABI: 64
    - COMPILER: MinGW-w64
      ABI: 32
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: Win32
 
build_script:
  - if [%COMPILER%]==[MinGW-w64] C:\msys64\usr\bin\sh.exe --login /c/projects/mpir/.appveyor_msys_build.sh
  - if [%COMPILER%]==[MSVC15] cd build.vc14
  - if [%COMPILER%]==[MSVC15] msbuild.bat gc lib %PLATFORM% %BUILD_TYPE% +tests

test_script:
  - if [%COMPILER%]==[MSVC15] cd mpir-tests
  - if [%COMPILER%]==[MSVC15] python %cd%\run-tests.py 0
